### ISSUE TITLE
Critique from Dr. Kane

### ISSUE THREAD

**Issue by kaneplusplus** [wyliadrian/BIS-687#1]
Great motivation.

Strong scientific questions and proposed interventions.

Comments:

1. How are you going to interpret the random forest results?
2. How were the cutoffs chosen for intensity?

**Comment by bonnieeeeeee** [comment]
For Question 1:
The mean squared error can be used to evaluate the model performance. A lower value indicates a better model. The feature importance scores generated by the random forest will enable us to evaluate how much the activity level scores contribute to the prediction of variables related to sleep quality, relative to other variables. This outcome will enable us to assess whether this variable is a significant factor in the connection between physical activity and sleep health. The mean squared error can be used to evaluate the model performance.

**Comment by xyqiuchloe** [comment]
2. Upon analyzing the Actigraphy data obtained from UK Biobank, we have observed three distinct peaks of milli-gravities when plotting histograms of activity milli-gravities against activity frequencies. Therefore, we decided to use these peaks as our identified cutoffs of activity intensity.
