### ISSUE TITLE
Critique comment from Yanjun Wu

### ISSUE THREAD

**Issue by Inkaa8** [wyliadrian/BIS-687#2]
Excellent project and presentation!

Comment:

In the class, the team addressed my question "What variables do you use to analyze accelerometry data? And how do you process them?"

Besides, my team also needs to use physical activity data. Your methods to treat them provide meaningful insights for us! Thank you!

**Comment by wyliadrian** [comment]
The variables are divided into 6 categories. The accelerometry data are from "Actigraphy". There are a bunch of variables such as "fraction_acceleration_900_milligravities_f90147_0_0", which indicates the fraction of acceleration <= 900 milli-gravities. They can be transformed into a density function of acceleration. After choosing the cutoffs, we determined the ranges for activities with different levels of intensity. By summing up them respectively, we obtained the scores for different kinds of activities.
