### ISSUE TITLE
Comments and Questions from Dwight

### ISSUE THREAD

**Issue by zichun-xu** [wyliadrian/BIS-687#4]
Thank you for your nice presentation on Wednesday, and I really like your clear and well-structured proposal! However, I do have the following two questions:

1. In your first aim, you will be conducting multiple t-tests to test the association between physical activities and sleep. How many tests exactly are you doing? If the number of statistical test is large, one needs to consider multiple hypothesis testing procedures to control the type I error. What is your strategy to control the type I error?
2. In your second aim, you will use a random forest to build a predictive model to predict sleep quality from physical activities and other covariates. Is there a specific reason why chose this model over other machine learning models (for example, neural networks or support vector machines)?

Thank you!!!

**Comment by bonnieeeeeee** [comment]
1.
The independent and dependent variables are shown as follows.
Independent variables (one at a time): high activity scores, low activity scores, medium activity scores
Dependent variables (one at a time): "getting_up_in_morning”, "morningevening_person_chronotype", "nap_during_day", "sleeplessness_insomnia", "snoring", "daytime_dozing_sleeping_narcolepsy", "trouble_falling_or_staying_asleep_or_sleeping_too_much" , "did_your_sleep_change", "trouble_falling_asleep", "sleeping_too_much" , "waking_too_early", "degree_bothered_by_trouble_sleeping_in_the_last_3_months"

Therefore, there should be 36 tests to be done. We will not have multiple outcomes at the same time. We will analyze each test's results separately, so there is no concern about type I error.

**Comment by xyqiuchloe** [comment]
2. The random forest model is a rather efficient model in handling feature engineering and is capable of providing us feature importance. These all fit purposes of our aims well and fulfills the needs. Thus we decided to use random forest.
