### ISSUE TITLE
Comments and Questiond from Han

### ISSUE THREAD

**Issue by hanxu900** [wyliadrian/BIS-687#5]
Great project and presentation! The research question is meaningful and novel. The aims and methods are clear.

In the class, your team addressed my question "Why did you choose random forest? How do you plan to measure model performance?"

Love your project! Keep the good work! Thank you!

**Comment by xyqiuchloe** [comment]
1. The random forest model is a rather efficient model in handling feature engineering and is capable of providing us feature importance. These all fit purposes of our aims well and fulfills the needs. Thus we decided to use random forest. 

2. To measure the model performance, we will use mean squared error. A lower value indicates a better model. The feature importance scores generated by the random forest will enable us to evaluate how much the activity level scores contribute to the prediction of variables related to sleep quality, relative to other variables. This outcome will enable us to assess whether this variable is a significant factor in the connection between physical activity and sleep health.
